version: "3"
services: 
  netquest-api:
    image: netquest-api:latest
    container_name: netquest-api-container
    ports:
      - 8000:8000
    env_file: ./.env
    build: .
    expose:
      - 8000
    depends_on:
      - postgres
  postgres:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: records
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql
volumes:
  postgres-data: